

lang = "ru"  # Можно менять на "en"

if lang == "ru":
    enter_team_name = "Введите название команды {}: "
    lives = "Жизни"
    score = "Очки"
    search_room = "Обыскать комнату"
    interrogate = "Допрашивать свидетелей"
    hack_computer = "Взломать компьютер"
    experiment = "Провести эксперимент"
    make_guess = "Сделать предположение"
    view_hints = "Просмотреть подсказки"
    choose_action = "Выберите действие (1-6): "
    found_clue = "Найдена подсказка: {}"
    no_new_clues = "Нет новых подсказок"
    trap_triggered = "Вы попали в ловушку! Потеряна одна жизнь."
    correct_guess = "Правильный ответ! Вы угадали {}."
    wrong_guess = "Неправильный ответ! Это не {}."
    already_guessed = "Этот элемент уже был угадан."
    team_eliminated = "Команда {} выбыла из игры!"
    game_over = "Игра окончена! Победила команда {}!"
    final_answers = "Правильные ответы: Орудие - {}, Место - {}, Мотив - {}"
elif lang == "en":
    enter_team_name = "Enter team name {}: "
    lives = "Lives"
    score = "Score"
    search_room = "Search the room"
    interrogate = "Interrogate witnesses"
    hack_computer = "Hack the computer"
    experiment = "Conduct an experiment"
    make_guess = "Make a guess"
    view_hints = "View hints"
    choose_action = "Choose an action (1-6): "
    found_clue = "Found a clue: {}"
    no_new_clues = "No new clues available"
    trap_triggered = "You triggered a trap! Lost one life."
    correct_guess = "Correct! You guessed the {}."
    wrong_guess = "Incorrect! This is not the {}."
    already_guessed = "This has already been guessed."
    team_eliminated = "Team {} has been eliminated!"
    game_over = "Game over! Team {} wins!"
    final_answers = "Correct answers: Weapon - {}, Location - {}, Motive - {}"
